name: Build Docker images and push

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: arm32
            docker_arch: arm
          - arch: arm32hf
            docker_arch: arm
          - arch: arm32v7
            docker_arch: arm/v7
          - arch: arm32v7hf
            docker_arch: arm/v7
          - arch: arm64
            docker_arch: arm64
          - arch: i586
            docker_arch: 386
          - arch: i686
            docker_arch: 386
          - arch: loong64
            docker_arch: loong64
          - arch: m68k
            docker_arch: m68k
          - arch: microblaze
            docker_arch: microblaze
          - arch: microblazeel
            docker_arch: microblazeel
          - arch: mips32
            docker_arch: mips
          - arch: mips32el
            docker_arch: mipsel
          - arch: mips32elsf
            docker_arch: mipsel
          - arch: mips32sf
            docker_arch: mips
          - arch: mips64
            docker_arch: mips64
          - arch: mips64el
            docker_arch: mips64el
          - arch: powerpc
            docker_arch: ppc
          - arch: powerpc64
            docker_arch: ppc64
          - arch: riscv32
            docker_arch: riscv32
          - arch: riscv64
            docker_arch: riscv64
          - arch: s390x
            docker_arch: s390x
          - arch: sh
            docker_arch: sh
          - arch: sheb
            docker_arch: sh
          - arch: x86_64
            docker_arch: amd64
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get release version
      id: vars
      run: |
        echo "version=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/${{ matrix.docker_arch }}
        build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            ARCH=${{ matrix.arch }}
        push: true
        tags: |
            ${{ env.IMAGE_NAMESPACE }}/natmap:${{ steps.vars.outputs.version }}-${{ matrix.arch }}
            ${{ env.IMAGE_NAMESPACE }}/natmap:latest-${{ matrix.arch }}
