name: Build Docker images and push

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            docker_arch: x86_64
          - arch: arm64
            docker_arch: arm64
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get release version
      id: vars
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/heiher/natmap/releases/latest | jq -r .tag_name)
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="master"
        fi
        echo "version=$LATEST_TAG" >> $GITHUB_OUTPUT
        echo "Using version: $LATEST_TAG"

    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        platforms: linux/${{ matrix.arch }}
        build-args: |
          VERSION=${{ steps.vars.outputs.version }}
          ARCH=${{ matrix.docker_arch }}
        tags: |
          ${{ env.IMAGE_NAMESPACE }}/natmap:${{ steps.vars.outputs.version }}-${{ matrix.arch }}
          ${{ env.IMAGE_NAMESPACE }}/natmap:latest-${{ matrix.arch }}
